version: '3.9'

services:

  db:
    image: mysql
    networks:
      - mi_red
    container_name: midbcompose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micurso
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  app:
    build: ./server_api
    depends_on:
      - db
    networks:
      - mi_red
    container_name: servidorcompose
    environment:
      DB_HOST: midbcompose
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: micurso
    working_dir: /app
    volumes:
      - ./server_api:/app
    ports:
      - "8001:8000"

volumes:
  db_data:
networks:
  mi_red:
